# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app
spec:
  selector:
    matchLabels:
      app: todo-app
  replicas: 1
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      containers:
        - name: todo-app
          image: docker.io/library/todo-app:prod
          imagePullPolicy: Never  
          ports:
          - containerPort: 80  
          env:
            - name: DATABASE_NAME
              valueFrom:
                secretKeyRef:
                  name: mysecret # this will be the name of your secret
                  key: database-name # and the key for this particular value
            - name: MONGO_DB_CONNECTION
              valueFrom:
                secretKeyRef:
                  name: mysecret
                  key: mongo-db-connection
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: mysecret
                  key: secret-key
            - name: OAUTH_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: mysecret
                  key: client-id
            - name: OAUTH_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: mysecret
                  key: client-secret
            - name: PORT
              valueFrom:
                secretKeyRef:
                  name: mysecret
                  key: port
            