# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app
spec:
  selector:
    matchLabels:
      app: to-do-app
  replicas: 1
  template:
    metadata:
      labels:
        app: to-do-app
    spec:
      containers:
        - name: todo-app
          image: docker.io/library/todo-app:prod
          imagePullPolicy: Never  
          ports:
          - containerPort: 7080  
          env:
            - name: DATABASE_NAME
              valueFrom:
                secretKeyRef:
                  name: database-name # this will be the name of your secret
                  key: databaseNameValue # and the key for this particular value
            - name: MONGO_DB_CONNECTION
              valueFrom:
                secretKeyRef:
                  name: mongo-db-connection
                  key: mongoDbConnectionValue
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: secret-key
                  key: secretKeyValue
            - name: CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: client-id
                  key: clientIdValue
            - name: GITHUB_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: client-secret
                  key: clientSecretValue
            - name: PORT
              value: "7080"
            