
apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
stringData:
  database-name: kamolsahamongo  
  
  mongo-db-connection: mongodb://kamolsahamongo:NeLEHTV8Tmny6lpffYAHrZOiDm8gceLz0iLqlj5WwpTUZqU0mp3lUCwJKF2EDqdsaUl9fK0rWGfl40ZobliAAQ==@kamolsahamongo.mongo.cosmos.azure.com:10255/?ssl=true&replicaSet=globaldb&retrywrites=false&maxIdleTimeMS=120000&appName=@kamolsahamongo@

  secret-key: secret-key

  client-id: a40204a3c886e5b6441d

  client-secret: 823f2dd80b2ae2dd65aee9f3c4d1f99becb49b72
  
  port: "80"

