name: To Do app CI & CD
on: [push, pull_request]

jobs:

    steps:
    - run: docker login  --username kamolsavar --password ${{secrets.password}}
    - run: docker build --target production --tag kamolsavar/heroku:latest .
    - run: docker push kamolsavar/heroku:latest

  test:
    name: Test
    runs-on: ubuntu-latest
    env:
      TOKEN: ${{ secrets.trelloToken}}
      KEY: ${{ secrets.trelloKey}}
      SECRET_KEY: ${{ secrets.trelloSecretKey}}
    steps:
    - uses: actions/checkout@v2
    - name: Build test image
      run: docker build --tag travis_todo:latest --target test .
    - name: Run unit test
      run: docker run travis_todo todo_app/test/test_unit.py
    - name: Run integration test
      run: docker run --env-file .env.test travis_todo todo_app/test/test_appTest.py
    - name: Run end-to-end test
      # You'll need to adjust this to also pass in the relevant environment variables
      run: docker run --env TOKEN --env KEY --env  SECRET_KEY travis_todo todo_app/test/test_appUiTest.py